### ISSUE TITLE
Ubah jadi MD bang

### ISSUE THREAD

**Issue by unknowkzr** [FadliDarmawan/haruno#11]
Kalo bisa sih ubah jadi MD 🗿🙏

**Comment by FadliDarmawan** [comment]
sebenernya w udah bikin repositori nya
https://github.com/FadliDarmawan/haruka

tapi belom ada kesempatan buat nge update. secara garis besar sama sc nya kayak haruno, cuma lebih simple aja ga ada kek fitur game walau ga menutup kemungkinan kedepannya ada
