### ISSUE TITLE
Cara ngubahnya gimana?

### ISSUE THREAD

**Issue by oneechan123** [FadliDarmawan/haruno#13]
![IMG_20220108_214054](https://user-images.githubusercontent.com/73242335/148648493-dccf45d3-ddba-4cbb-b71b-9a3647807821.jpg)
Cara ngubah "global.thumbfoto" ke "global.fla" gimana? Soalnya klo pake https://telegra.ph suka eror menunya

**Comment by oneechan123** [comment]
> ![IMG_20220108_214054](https://user-images.githubusercontent.com/73242335/148648493-dccf45d3-ddba-4cbb-b71b-9a3647807821.jpg) Cara ngubah "global.thumbfoto" ke "global.fla" gimana? Soalnya klo pake https://telegra.ph suka eror menunya

![IMG_20220108_222457](https://user-images.githubusercontent.com/73242335/148649858-d5e4dfe5-873b-4d27-9781-2075bffcda01.jpg)
Kyk gini mulu

**Comment by FadliDarmawan** [comment]
![Screenshot_20220110-070050_GitHub.jpg](https://user-images.githubusercontent.com/79369935/148706538-7a227f83-343a-4a7e-b818-242f626a0e34.jpg)

(thumbfoto) ubah jadi (fla + teks)
