### ISSUE TITLE
Welcome & Leave

### ISSUE THREAD

**Issue by oneechan123** [FadliDarmawan/haruno#14]
![IMG_20220112_014247](https://user-images.githubusercontent.com/73242335/149002593-89ac8df3-090c-4dcb-b5f5-cd36680968c3.jpg)
Cara ngubah jadi Profile biasa bisa gk? Klo kyk gini suka gk muncul

**Comment by FadliDarmawan** [comment]
> ![IMG_20220112_014247](https://user-images.githubusercontent.com/73242335/149002593-89ac8df3-090c-4dcb-b5f5-cd36680968c3.jpg) Cara ngubah jadi Profile biasa bisa gk? Klo kyk gini suka gk muncul

kalau udah pake versi terbaru yang 2.3.8 ke atas harusnya udah aman welcome/leave nya.

tapi kalau mau pake pp doang ya ubah jadi conn.sendFile
