### ISSUE TITLE
ButtonImg

### ISSUE THREAD

**Issue by FadliDarmawan** [FadliDarmawan/haruno#4]
sendButtonImg parameter nya di ubah menjadi
gambar, teks, footer, button, cmd, option

dulu nya: teks, gambar, footer, button, cmd, option

**Comment by oneechan123** [comment]
> sendButtonImg parameter nya di ubah menjadi
> gambar, teks, footer, button, cmd, option
> 
> dulu nya: teks, gambar, footer, button, cmd, option

Ini dimana ngubanya?

**Comment by FadliDarmawan** [comment]
> > sendButtonImg parameter nya di ubah menjadi
> > gambar, teks, footer, button, cmd, option
> > 
> > dulu nya: teks, gambar, footer, button, cmd, option
> 
> Ini dimana ngubanya?

Ga usah, sekalian aku yang update aja besok (mungkin klo sempet)
