### ISSUE TITLE
Bagi

### ISSUE THREAD

**Issue by oneechan123** [FadliDarmawan/haruno#5]
Bagi button lokasi, punya gw OVERSIZED

**Comment by FadliDarmawan** [comment]
> Bagi button lokasi, punya gw OVERSIZED

oversized?

**Comment by oneechan123** [comment]
> > Bagi button lokasi, punya gw OVERSIZED
> 
> oversized?

![Uploading IMG_20210831_123101.jpg…]()
Gini

**Comment by FadliDarmawan** [comment]
> Bagi button lokasi, punya gw OVERSIZED

file gambar nya yang kecil, jangan terlalu besar. atau bisa di kompres, banyak tu di web
