### ISSUE TITLE
sendButtonLoc

### ISSUE THREAD

**Issue by oneechan123** [FadliDarmawan/haruno#6]
Bagi case fitur yg pake lokasi dong

**Comment by FadliDarmawan** [comment]
> Bagi case fitur yg pake lokasi dong

![Screen Shot 2021-08-31 at 20 47 04](https://user-images.githubusercontent.com/79369935/131514218-bd259591-9366-4f7b-9f80-10cbd2263351.png)


udah ada di situ contoh nya
conn.sendButtonLoc(m.chat, gambar buffer, teks, footer, button, command)

bisa di lihat di menu.js
